### ISSUE TITLE
Error when testing yolov5

### ISSUE THREAD

**Issue by jiao1234567** [tianyic/only_train_once#45] opened 2023-12-28 09:53 UTC
Thank you for your contribution. I added a detection head to yolov5, and when I tested it with OTO I got an error.

```
from only_train_once import OTO
import unittest
import os
import onnxruntime as ort
import numpy as np
from models.experimental import attempt_load

OUT_DIR = './cache'

class TestYolov5(unittest.TestCase):
    def test_sanity(self, dummy_input=torch.rand(1, 3, 640, 384, device='cuda:0')):
        model = attempt_load('baseline_model/best.pt', map_location=torch.device('cuda:0'), fuse=False)
        # All parameters in the pretrained Yolov5 are not trainable.
        for _, param in model.named_parameters():
            param.requires_grad = True

        oto = OTO(model, dummy_input)
        oto.mark_unprunable_by_node_ids(
            # ['node-229', 'node-329', 'node-443', 'node-553']
            ['node-229', 'node-581', 'node-471', 'node-359']
        )
        oto.visualize(view=False, out_dir=OUT_DIR)
        optimizer = oto.hesso(
            variant='sgd',
            lr=0.1
        )
        oto.random_set_zero_groups()
        # YOLOv5 has some trouble to directly load torch model
        oto.construct_subnet(
            out_dir=OUT_DIR,
            ckpt_format='onnx'
        )

        full_sess = ort.InferenceSession(oto.full_group_sparse_model_path)
        full_output = full_sess.run(None, {'onnx::Cast_0': dummy_input.numpy()})
        compressed_sess = ort.InferenceSession(oto.compressed_model_path)
        compressed_output = compressed_sess.run(None, {'onnx::Cast_0': dummy_input.numpy()})

        max_output_diff = np.max(np.abs(full_output[0] - compressed_output[0]))
        print("Maximum output difference " + str(max_output_diff.item()))
        self.assertLessEqual(max_output_diff, 1e-3)

        full_model_size = os.stat(oto.full_group_sparse_model_path)
        compressed_model_size = os.stat(oto.compressed_model_path)
        print("Size of full model     : ", full_model_size.st_size / (1024 ** 3), "GBs")
        print("Size of compress model : ", compressed_model_size.st_size / (1024 ** 3), "GBs")

os.makedirs(OUT_DIR, exist_ok=True)
    
if __name__ == '__main__':
    unittest.main()
```

```
OTO graph constructor
graph build
/home/code/yolo/models/yolo.py:63: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
/home/code/yolo/models/yolo.py:85: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  y, x = torch.tensor(y, device=d, dtype=t), torch.tensor(x, device=d, dtype=t)
/home/code/yolo/models/yolo.py:120: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
/home/code/yolo/models/yolo.py:149: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  y, x = torch.tensor(y, device=d, dtype=t), torch.tensor(x, device=d, dtype=t)
/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py:429: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(torch.__version__) >= LooseVersion('1.9.0') and \
/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py:430: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LooseVersion(torch.__version__) <= LooseVersion('1.11.10'):
/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py:432: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  elif LooseVersion(torch.__version__) >= LooseVersion('1.13.0'):
E
======================================================================
ERROR: test_sanity (__main__.TestYolov5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "train_oto.py", line 18, in test_sanity
    oto = OTO(model, dummy_input)
  File "/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/__init__.py", line 17, in __init__
    self.initialize(model=self._model, dummy_input=self._dummy_input, skip_patterns=self._skip_patterns, strict_out_nodes=self._strict_out_nodes)
  File "/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/__init__.py", line 36, in initialize
    self._graph = Graph(model, dummy_input, skip_patterns=skip_patterns, strict_out_nodes=strict_out_nodes)
  File "/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py", line 61, in __init__
    self.build(model, dummy_input)
  File "/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py", line 70, in build
    trace_graph = self._get_trace_graph(model, dummy_input, optimized_onnx=self.trace_onnx)
  File "/home/miniconda3/envs/yolo/lib/python3.8/site-packages/only_train_once/graph/graph.py", line 435, in _get_trace_graph
    raise "Torch {} is not supported because of some bug in _optimize_trace.".format(torch.__version__)
TypeError: exceptions must derive from BaseException

----------------------------------------------------------------------
Ran 1 test in 4.361s

FAILED (errors=1)
```

**Comment by tianyic** [comment] 2023-12-28 17:08
Thanks for reaching out. The error looks like your torch version is not supported yet. Could you provide the torch version?

**Comment by jiao1234567** [comment] 2023-12-29 02:05
Thank you for your reply. The version I use is torch1.12.1, onnx1.15.0, only_train_once3.0.0. Also I would like to ask how mark_unprunable_by_node_ids is determined, and if don't add the mark_unprunable_by_node_ids parameter, will it have any effect?

**Comment by tianyic** [comment] 2023-12-29 06:17
`torch==1.12` is not supported by OTO. We recommend to upgrade `torch>=2.0`. 

Marking node groups as unprunable is to skip unsupported pattern and focuses on pruning over the remaining sub-graphs. For Yolov5, the skipped node-groups could be found at [yolo_v5](https://github.com/tianyic/only_train_once/blob/main/visual_examples/pruning/yolov5.pdf). Ideally and typically, there is no need to manually set up such stuffs. The principle for setup is to write a sanity check over a DNN. During sanity check, if there exists some error happening during sub-network validation, mark the node groups corresponding to where the errors came from is a common routine to mark unprunable to see if the sanity check could pass. Different torch version may have varying node-ids, thereby may need to some adjustments. 

Meanwhile, the potential efforts of setting up unprunable node groups could be gradually relieved following the further developments and evolutions of pruning dependency graph. Current graph analysis in both OTO and torch-pruning still have room for advanced automation.

**Comment by jiao1234567** [comment] 2023-12-29 09:24
thanks, it works. I have tried torch-pruning before, but the results are not rational, for yolov5 pruning 30% accuracy degradation will be more serious, have you tried to compare OTO and torch-pruning on yolov5?

**Comment by tianyic** [comment] 2023-12-29 12:21
@jiao1234567  Glad to hear it works. 

For accuracy, I assume that you used the optimizer setup presented in the [tutorial for resnet18 cifar10](https://github.com/tianyic/only_train_once/blob/main/tutorials/01.resnet18_cifar10.ipynb). I would say you may want to try fine-tune the [hyperparameters](https://github.com/tianyic/only_train_once/blob/main/only_train_once/optimizer/hesso.py) to make it competitive. We recommend to set up the hyperparameters to be exactly the same as the baseline optimizer. Meanwhile, some experiments need to enlarge training steps for convergence.

I personally did not try Yolov5 due to limited bandwidth, yet one of my colleagues tried OTO on YOLO over COCO. Actually target-group-sparsity as 0.3 if that is the pruning ratio you used should not have significant acc degradation based on his experience if training pipeline is properly setup . See the below table and curve. 

![IMG_0083](https://github.com/tianyic/only_train_once/assets/8930611/0c074934-bf01-4ef8-a391-c084de88569c)
![IMG_0084](https://github.com/tianyic/only_train_once/assets/8930611/99392087-e872-43ca-ab5a-b50e0426c93e)

**Comment by tianyic** [comment] 2023-12-29 13:37
Closed as the topic has been completed. Feel free to open a new issue regarding accuracy if still have regression. Our official tutorial on yolo will be released on the early of next year along with the release of HESSO optimizer technical report.

**Closed by tianyic** 2023-12-29 13:37 UTC
